import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Row, Col } from 'reactstrap'
import { Layout } from '../components/Layout'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Florian Winkler • CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container>
          <Row>
            <Col md={ 6 }>
              <h1 className={styles.title}>
                About 
              </h1>
            </Col>
            <Col md={ 6 }>
              <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos eos deserunt sunt ullam. Quod, quaerat a voluptatem perspiciatis perferendis maiores.
              </p>
            </Col>  
          </Row>
        </Container>
      </Layout>
    </div>
  )
}

export default About
