import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/Layout'
import styles from '../styles/Home.module.css'

const Projects: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Florian Winkler • Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className={styles.title}>
          Projects 
        </h1>
      </Layout>
    </div>
  )
}

export default Projects
